import { registerElement } from "../react/host-config.ts";

import { BoxWidget, ScrollableBoxWidget } from "./box.ts";
import { ButtonWidget } from "./button.ts";
import { CheckboxWidget } from "./checkbox.ts";
import { DockWidget } from "./dock.ts";
import { FooterWidget } from "./footer.ts";
import { GridWidget } from "./grid.ts";
import { HBoxWidget } from "./hbox.ts";
import { HeaderWidget } from "./header.ts";
import { IconWidget } from "./icon.ts";
import { ImageWidget } from "./image.ts";
import { InputWidget } from "./input.ts";
import { JSONUIWidget } from "./json-ui.ts";
import { LabelWidget } from "./label.ts";
import { MarkdownWidget } from "./markdown.ts";
import { MermaidWidget } from "./mermaid.ts";
import { RadioGroupWidget } from "./radio-group.ts";
import { RichTextWidget } from "./rich-text.ts";
import { SelectWidget } from "./select.ts";
import { SliderWidget } from "./slider.ts";
import { SvgImageWidget } from "./svg-image.ts";
import { SwitchWidget } from "./switch.ts";
import { SyntaxWidget } from "./syntax.ts";
import { TabContainerWidget } from "./tabcontainer.ts";
import { TextAreaWidget } from "./textarea.ts";
import { ToggleButtonWidget } from "./toggle-button.ts";
import { VBoxWidget } from "./vbox.ts";

export { BoxWidget, ScrollableBoxWidget } from "./box.ts";
export { ButtonWidget } from "./button.ts";
export { CheckboxWidget } from "./checkbox.ts";
export { DockWidget } from "./dock.ts";
export { FooterWidget } from "./footer.ts";
export { GridWidget } from "./grid.ts";
export { HBoxWidget } from "./hbox.ts";
export { HeaderWidget } from "./header.ts";
export { IconWidget } from "./icon.ts";
export { ImageWidget } from "./image.ts";
export { InputWidget } from "./input.ts";
export { JSONUIWidget } from "./json-ui.ts";
export { LabelWidget } from "./label.ts";
export { MarkdownWidget } from "./markdown.ts";
export { MermaidWidget } from "./mermaid.ts";
export { RadioGroupWidget } from "./radio-group.ts";
export { RichTextWidget } from "./rich-text.ts";
export { SelectWidget } from "./select.ts";
export { SliderWidget } from "./slider.ts";
export { SvgImageWidget } from "./svg-image.ts";
export { SwitchWidget } from "./switch.ts";
export { SyntaxWidget } from "./syntax.ts";
export { TabContainerWidget } from "./tabcontainer.ts";
export { TextAreaWidget } from "./textarea.ts";
export { ToggleButtonWidget } from "./toggle-button.ts";
export { VBoxWidget } from "./vbox.ts";

registerElement("ztui-box", () => new BoxWidget());
registerElement("ztui-scrollable-box", () => new ScrollableBoxWidget());
registerElement("ztui-label", () => new LabelWidget());
registerElement("ztui-button", () => new ButtonWidget());
registerElement("ztui-input", () => new InputWidget());
registerElement("ztui-textarea", () => new TextAreaWidget());
registerElement("ztui-header", () => new HeaderWidget());
registerElement("ztui-footer", () => new FooterWidget());
registerElement("ztui-vbox", () => new VBoxWidget());
registerElement("ztui-hbox", () => new HBoxWidget());
registerElement("ztui-grid", () => new GridWidget());
registerElement("ztui-dock", () => new DockWidget());
registerElement("ztui-icon", () => new IconWidget());
registerElement("ztui-image", () => new ImageWidget());
registerElement("ztui-svgimage", () => new SvgImageWidget());
registerElement("ztui-richtext", () => new RichTextWidget());
registerElement("ztui-syntax", () => new SyntaxWidget());
registerElement("ztui-markdown", () => new MarkdownWidget());
registerElement("ztui-jsonui", () => new JSONUIWidget());
registerElement("ztui-mermaid", () => new MermaidWidget());
registerElement("mermaid", () => new MermaidWidget());
registerElement("ztui-select", () => new SelectWidget());
registerElement("ztui-radio-group", () => new RadioGroupWidget());
registerElement("ztui-checkbox", () => new CheckboxWidget());
registerElement("ztui-switch", () => new SwitchWidget());
registerElement("ztui-slider", () => new SliderWidget());
registerElement("ztui-toggle-button", () => new ToggleButtonWidget());
registerElement("ztui-tabcontainer", () => new TabContainerWidget());
