import { registerElement } from "../react/host-config.ts";

import { BoxWidget } from "./box.ts";
import { ButtonWidget } from "./button.ts";
import { DockWidget } from "./dock.ts";
import { FooterWidget } from "./footer.ts";
import { GridWidget } from "./grid.ts";
import { HBoxWidget } from "./hbox.ts";
import { HeaderWidget } from "./header.ts";
import { IconWidget } from "./icon.ts";
import { ImageWidget } from "./image.ts";
import { InputWidget } from "./input.ts";
import { LabelWidget } from "./label.ts";
import { SvgImageWidget } from "./svg-image.ts";
import { VBoxWidget } from "./vbox.ts";

export { BoxWidget } from "./box.ts";
export { ButtonWidget } from "./button.ts";
export { DockWidget } from "./dock.ts";
export { FooterWidget } from "./footer.ts";
export { GridWidget } from "./grid.ts";
export { HBoxWidget } from "./hbox.ts";
export { HeaderWidget } from "./header.ts";
export { IconWidget } from "./icon.ts";
export { ImageWidget } from "./image.ts";
export { InputWidget } from "./input.ts";
export { LabelWidget } from "./label.ts";
export { SvgImageWidget } from "./svg-image.ts";
export { VBoxWidget } from "./vbox.ts";

registerElement("ztui-box", () => new BoxWidget());
registerElement("ztui-label", () => new LabelWidget());
registerElement("ztui-button", () => new ButtonWidget());
registerElement("ztui-input", () => new InputWidget());
registerElement("ztui-header", () => new HeaderWidget());
registerElement("ztui-footer", () => new FooterWidget());
registerElement("ztui-vbox", () => new VBoxWidget());
registerElement("ztui-hbox", () => new HBoxWidget());
registerElement("ztui-grid", () => new GridWidget());
registerElement("ztui-dock", () => new DockWidget());
registerElement("ztui-icon", () => new IconWidget());
registerElement("ztui-image", () => new ImageWidget());
registerElement("ztui-svgimage", () => new SvgImageWidget());
