import { OverlayRootWidget } from "../dom/overlay.ts";
import { registerElement } from "../react/host-config.ts";
import { ButtonWidget } from "./controls/button.ts";
import { CheckboxWidget } from "./controls/checkbox.ts";
import { FieldErrorWidget } from "./controls/field-error.ts";
import { FormWidget } from "./controls/form.ts";
import { InputWidget } from "./controls/input.ts";
import { ProgressBarWidget } from "./controls/progress-bar.ts";
import { RadioGroupWidget } from "./controls/radio-group.ts";
import { SelectWidget } from "./controls/select.ts";
import { SliderWidget } from "./controls/slider.ts";
import { SpinnerWidget } from "./controls/spinner.ts";
import { StatusBadgeWidget, StatusDotWidget, StatusListWidget } from "./controls/status.ts";
import { SwitchWidget } from "./controls/switch.ts";
import { TextAreaWidget } from "./controls/textarea.ts";
import { ToggleButtonWidget } from "./controls/toggle-button.ts";
import { ValidationSummaryWidget } from "./controls/validation-summary.ts";
import { WaitingGridWidget } from "./controls/waiting-grid.ts";
import { WaitingPanelWidget } from "./controls/waiting-panel.ts";
import { DiffWidget } from "./data/diff.ts";
import { ListViewWidget } from "./data/list-view.ts";
import { RichLogWidget } from "./data/rich-log.ts";
import { SelectionListWidget } from "./data/selection-list.ts";
import { SparklineWidget } from "./data/sparkline.ts";
import { TableCellWidget, TableWidget } from "./data/table.ts";
import { TerminalViewWidget } from "./data/terminal-view.ts";
import { TracebackWidget } from "./data/traceback.ts";
import { TreeWidget } from "./data/tree.ts";
import { AttentionWidget } from "./layout/attention.ts";
import { BoxWidget, ScrollableBoxWidget } from "./layout/box.ts";
import { CollapsibleWidget } from "./layout/collapsible.ts";
import { DividerWidget } from "./layout/divider.ts";
import { DockWidget } from "./layout/dock.ts";
import { FooterWidget } from "./layout/footer.ts";
import { GridWidget } from "./layout/grid.ts";
import { HBoxWidget } from "./layout/hbox.ts";
import { HeaderWidget } from "./layout/header.ts";
import { SplitterWidget } from "./layout/splitter.ts";
import { TabContainerWidget } from "./layout/tabcontainer.ts";
import { VBoxWidget } from "./layout/vbox.ts";
import { FileIconWidget } from "./media/file-icon.ts";
import { IconWidget } from "./media/icon.ts";
import { ImageWidget } from "./media/image.ts";
import { SvgImageWidget } from "./media/svg-image.ts";
import { JSONUIWidget } from "./text/json-ui.ts";
import { LabelWidget } from "./text/label.ts";
import { MarkdownWidget } from "./text/markdown.ts";
import { MermaidWidget } from "./text/mermaid.ts";
import { RichTextWidget } from "./text/rich-text.ts";
import { SyntaxWidget } from "./text/syntax.ts";

export { ButtonWidget } from "./controls/button.ts";
export { CheckboxWidget } from "./controls/checkbox.ts";
export { FieldErrorWidget } from "./controls/field-error.ts";
export { type FormMessageMode, FormWidget } from "./controls/form.ts";
export { InputWidget } from "./controls/input.ts";
export { ProgressBarWidget } from "./controls/progress-bar.ts";
export { RadioGroupWidget } from "./controls/radio-group.ts";
export { SelectWidget } from "./controls/select.ts";
export { SliderWidget } from "./controls/slider.ts";
export { type SpinnerMode, SpinnerWidget } from "./controls/spinner.ts";
export {
  type GlyphSet,
  StatusBadgeWidget,
  StatusDotWidget,
  type StatusListItem,
  StatusListWidget,
  type StatusState,
  statusGlyph,
} from "./controls/status.ts";
export { SwitchWidget } from "./controls/switch.ts";
export { TextAreaWidget } from "./controls/textarea.ts";
export { ToggleButtonWidget } from "./controls/toggle-button.ts";
export * from "./controls/validation.ts";
export { ValidationSummaryWidget } from "./controls/validation-summary.ts";
export {
  type WaitingGridCells,
  type WaitingGridVariant,
  WaitingGridWidget,
} from "./controls/waiting-grid.ts";
export { type WaitingPanelVariant, WaitingPanelWidget } from "./controls/waiting-panel.ts";
export { type DiffView, DiffWidget } from "./data/diff.ts";
export type { ListItem } from "./data/list-view.ts";
export { ListViewWidget } from "./data/list-view.ts";
export { RichLogWidget } from "./data/rich-log.ts";
export { type SelectionGlyphSet, SelectionListWidget } from "./data/selection-list.ts";
export { SparklineWidget } from "./data/sparkline.ts";
export type { SortDirection, SortState, TableColumn, TableTextStyle } from "./data/table.ts";
export { TableCellWidget, TableWidget } from "./data/table.ts";
export { TerminalViewWidget } from "./data/terminal-view.ts";
export { TracebackWidget } from "./data/traceback.ts";
export type { TreeNode } from "./data/tree.ts";
export { TreeWidget } from "./data/tree.ts";
export { AttentionWidget } from "./layout/attention.ts";
export { BoxWidget, ScrollableBoxWidget } from "./layout/box.ts";
export { type CollapsibleGlyphSet, CollapsibleWidget } from "./layout/collapsible.ts";
export { type DividerOrientation, DividerWidget } from "./layout/divider.ts";
export { DockWidget } from "./layout/dock.ts";
export { FooterWidget } from "./layout/footer.ts";
export { GridWidget } from "./layout/grid.ts";
export { HBoxWidget } from "./layout/hbox.ts";
export { HeaderWidget } from "./layout/header.ts";
export { type SplitterOrientation, SplitterWidget } from "./layout/splitter.ts";
export { TabContainerWidget } from "./layout/tabcontainer.ts";
export { VBoxWidget } from "./layout/vbox.ts";
export { FileIconWidget } from "./media/file-icon.ts";
export { IconWidget } from "./media/icon.ts";
export { ImageWidget } from "./media/image.ts";
export { SvgImageWidget } from "./media/svg-image.ts";
export { JSONUIWidget } from "./text/json-ui.ts";
export { LabelWidget } from "./text/label.ts";
export { MarkdownWidget } from "./text/markdown.ts";
export { MermaidWidget } from "./text/mermaid.ts";
export { RichTextWidget } from "./text/rich-text.ts";
export { SyntaxWidget } from "./text/syntax.ts";

registerElement("ztui-box", () => new BoxWidget());
registerElement("ztui-attention", () => new AttentionWidget());
registerElement("ztui-overlay-root", () => new OverlayRootWidget());
registerElement("ztui-scrollable-box", () => new ScrollableBoxWidget());
registerElement("ztui-label", () => new LabelWidget());
registerElement("ztui-button", () => new ButtonWidget());
registerElement("ztui-input", () => new InputWidget());
registerElement("ztui-form", () => new FormWidget());
registerElement("ztui-field-error", () => new FieldErrorWidget());
registerElement("ztui-validation-summary", () => new ValidationSummaryWidget());
registerElement("ztui-textarea", () => new TextAreaWidget());
registerElement("ztui-header", () => new HeaderWidget());
registerElement("ztui-footer", () => new FooterWidget());
registerElement("ztui-vbox", () => new VBoxWidget());
registerElement("ztui-hbox", () => new HBoxWidget());
registerElement("ztui-grid", () => new GridWidget());
registerElement("ztui-dock", () => new DockWidget());
registerElement("ztui-collapsible", () => new CollapsibleWidget());
registerElement("ztui-file-icon", () => new FileIconWidget());
registerElement("ztui-icon", () => new IconWidget());
registerElement("ztui-image", () => new ImageWidget());
registerElement("ztui-svgimage", () => new SvgImageWidget());
registerElement("ztui-richtext", () => new RichTextWidget());
registerElement("ztui-syntax", () => new SyntaxWidget());
registerElement("ztui-markdown", () => new MarkdownWidget());
registerElement("ztui-jsonui", () => new JSONUIWidget());
registerElement("ztui-mermaid", () => new MermaidWidget());
registerElement("mermaid", () => new MermaidWidget());
registerElement("ztui-listview", () => new ListViewWidget());
registerElement("ztui-richlog", () => new RichLogWidget());
registerElement("ztui-diff", () => new DiffWidget());
registerElement("ztui-sparkline", () => new SparklineWidget());
registerElement("ztui-selection-list", () => new SelectionListWidget());
registerElement("ztui-traceback", () => new TracebackWidget());
registerElement("ztui-terminal-view", () => new TerminalViewWidget());
registerElement("ztui-select", () => new SelectWidget());
registerElement("ztui-radio-group", () => new RadioGroupWidget());
registerElement("ztui-checkbox", () => new CheckboxWidget());
registerElement("ztui-switch", () => new SwitchWidget());
registerElement("ztui-slider", () => new SliderWidget());
registerElement("ztui-progress-bar", () => new ProgressBarWidget());
registerElement("ztui-spinner", () => new SpinnerWidget());
registerElement("ztui-status-dot", () => new StatusDotWidget());
registerElement("ztui-status-badge", () => new StatusBadgeWidget());
registerElement("ztui-status-list", () => new StatusListWidget());
registerElement("ztui-waiting-grid", () => new WaitingGridWidget());
registerElement("ztui-waiting-panel", () => new WaitingPanelWidget());
registerElement("ztui-toggle-button", () => new ToggleButtonWidget());
registerElement("ztui-table", () => new TableWidget());
registerElement("ztui-table-cell", () => new TableCellWidget());
registerElement("ztui-tree", () => new TreeWidget());
registerElement("ztui-tabcontainer", () => new TabContainerWidget());
registerElement("ztui-splitter", () => new SplitterWidget());
registerElement("ztui-divider", () => new DividerWidget());
