// Registers all core widget elements with the element registry. Imported by the
// `ztui` core entry and by the kitchen-sink `widgets/index.ts`. Excludes the
// optional text engines (markdown/syntax/mermaid), which register themselves via
// their own opt-in entries (`ztui/markdown`, `ztui/syntax`, `ztui/mermaid`).
import { registerElement } from "../dom/element-registry.ts";
import { OverlayRootWidget } from "../dom/overlay.ts";
import { ButtonWidget } from "./controls/button.ts";
import { ChatInputWidget } from "./controls/chat-input.ts";
import { CheckboxWidget } from "./controls/checkbox.ts";
import { FieldErrorWidget } from "./controls/field-error.ts";
import { FormWidget } from "./controls/form.ts";
import { InputWidget } from "./controls/input.ts";
import { MenuListWidget } from "./controls/menu.ts";
import { RadioGroupWidget } from "./controls/radio-group.ts";
import { SelectWidget } from "./controls/select.ts";
import { SliderWidget } from "./controls/slider.ts";
import { SwitchWidget } from "./controls/switch.ts";
import { TextAreaWidget } from "./controls/textarea.ts";
import { ToggleButtonWidget } from "./controls/toggle-button.ts";
import { ValidationSummaryWidget } from "./controls/validation-summary.ts";
import { BarChartWidget, LinePlotWidget } from "./data/chart.ts";
import { DiffWidget } from "./data/diff.ts";
import { ListViewWidget } from "./data/list-view.ts";
import { RichLogWidget } from "./data/rich-log.ts";
import { SelectionListWidget } from "./data/selection-list.ts";
import { SparklineWidget } from "./data/sparkline.ts";
import { TableCellWidget, TableWidget } from "./data/table.ts";
import { TerminalViewWidget } from "./data/terminal-view.ts";
import { TracebackWidget } from "./data/traceback.ts";
import { TreeWidget } from "./data/tree.ts";
import { BannerWidget } from "./feedback/banner.ts";
import { ProgressBarWidget } from "./feedback/progress-bar.ts";
import { SpinnerWidget } from "./feedback/spinner.ts";
import { StatusBadgeWidget, StatusDotWidget, StatusListWidget } from "./feedback/status.ts";
import { WaitingGridWidget } from "./feedback/waiting-grid.ts";
import { WaitingPanelWidget } from "./feedback/waiting-panel.ts";
import { AttentionWidget } from "./layout/attention.ts";
import { BoxWidget, ScrollableBoxWidget } from "./layout/box.ts";
import { CollapsibleWidget } from "./layout/collapsible.ts";
import { DividerWidget } from "./layout/divider.ts";
import { DockWidget } from "./layout/dock.ts";
import { FooterWidget } from "./layout/footer.ts";
import { GridWidget } from "./layout/grid.ts";
import { HBoxWidget } from "./layout/hbox.ts";
import { HeaderWidget } from "./layout/header.ts";
import { SplitterWidget } from "./layout/splitter.ts";
import { TabContainerWidget } from "./layout/tabcontainer.ts";
import { VBoxWidget } from "./layout/vbox.ts";
import { FileIconWidget } from "./media/file-icon.ts";
import { IconWidget } from "./media/icon.ts";
import { ImageWidget } from "./media/image.ts";
import { SvgImageWidget } from "./media/svg-image.ts";
import { JSONUIWidget } from "./text/json-ui.ts";
import { LabelWidget } from "./text/label.ts";
import { RichTextWidget } from "./text/rich-text.ts";

registerElement("ztui-box", () => new BoxWidget());
registerElement("ztui-attention", () => new AttentionWidget());
registerElement("ztui-overlay-root", () => new OverlayRootWidget());
registerElement("ztui-scrollable-box", () => new ScrollableBoxWidget());
registerElement("ztui-label", () => new LabelWidget());
registerElement("ztui-button", () => new ButtonWidget());
registerElement("ztui-input", () => new InputWidget());
registerElement("ztui-form", () => new FormWidget());
registerElement("ztui-field-error", () => new FieldErrorWidget());
registerElement("ztui-validation-summary", () => new ValidationSummaryWidget());
registerElement("ztui-textarea", () => new TextAreaWidget());
registerElement("ztui-chat-input", () => new ChatInputWidget());
registerElement("ztui-header", () => new HeaderWidget());
registerElement("ztui-footer", () => new FooterWidget());
registerElement("ztui-vbox", () => new VBoxWidget());
registerElement("ztui-hbox", () => new HBoxWidget());
registerElement("ztui-grid", () => new GridWidget());
registerElement("ztui-dock", () => new DockWidget());
registerElement("ztui-collapsible", () => new CollapsibleWidget());
registerElement("ztui-file-icon", () => new FileIconWidget());
registerElement("ztui-icon", () => new IconWidget());
registerElement("ztui-image", () => new ImageWidget());
registerElement("ztui-svgimage", () => new SvgImageWidget());
registerElement("ztui-richtext", () => new RichTextWidget());
registerElement("ztui-jsonui", () => new JSONUIWidget());
registerElement("ztui-listview", () => new ListViewWidget());
registerElement("ztui-richlog", () => new RichLogWidget());
registerElement("ztui-diff", () => new DiffWidget());
registerElement("ztui-sparkline", () => new SparklineWidget());
registerElement("ztui-bar-chart", () => new BarChartWidget());
registerElement("ztui-line-plot", () => new LinePlotWidget());
registerElement("ztui-selection-list", () => new SelectionListWidget());
registerElement("ztui-traceback", () => new TracebackWidget());
registerElement("ztui-terminal-view", () => new TerminalViewWidget());
registerElement("ztui-select", () => new SelectWidget());
registerElement("ztui-menu-list", () => new MenuListWidget());
registerElement("ztui-radio-group", () => new RadioGroupWidget());
registerElement("ztui-checkbox", () => new CheckboxWidget());
registerElement("ztui-switch", () => new SwitchWidget());
registerElement("ztui-slider", () => new SliderWidget());
registerElement("ztui-banner", () => new BannerWidget());
registerElement("ztui-progress-bar", () => new ProgressBarWidget());
registerElement("ztui-spinner", () => new SpinnerWidget());
registerElement("ztui-status-dot", () => new StatusDotWidget());
registerElement("ztui-status-badge", () => new StatusBadgeWidget());
registerElement("ztui-status-list", () => new StatusListWidget());
registerElement("ztui-waiting-grid", () => new WaitingGridWidget());
registerElement("ztui-waiting-panel", () => new WaitingPanelWidget());
registerElement("ztui-toggle-button", () => new ToggleButtonWidget());
registerElement("ztui-table", () => new TableWidget());
registerElement("ztui-table-cell", () => new TableCellWidget());
registerElement("ztui-tree", () => new TreeWidget());
registerElement("ztui-tabcontainer", () => new TabContainerWidget());
registerElement("ztui-splitter", () => new SplitterWidget());
registerElement("ztui-divider", () => new DividerWidget());
